data_directory: data/
num_epochs: 50
dataset:
    add_negative_train_samples: true
    disjoint_train_ratio: 0.3
    is_undirected: true
    neg_sampling_ratio: 3.0
    num_test: 0.1
    num_val: 0.1
loader:
    train:
        batch_size: 1024
        neg_sampling_ratio: 3.0
        num_neighbors:
        - 15
        - 10
        shuffle: true
    val_test:
        batch_size: 2048
        num_neighbors:
        - -1
        shuffle: false
model:
    hidden_channels: 128
    movie_feat_dim: 403
    num_movies: 85198
    num_users: 200948
    dropout: 0.15
optimizer:
    lr: 1e-03
    weight_decay: 1e-04
scheduler:
    mode: 'max'
    factor: 0.5
    patience: 3
    threshold: 1e-04
    min_lr: 1e-06
    verbose: true
