trainer:
    num_epochs: 50
    log_dir: "results/logs_16"
    mixed_precision: false
dataset:
    add_negative_train_samples: false
    disjoint_train_ratio: 0.3
    is_undirected: true
    num_test: 0.1
    num_val: 0.1
loader:
    train:
        batch_size: 1024
        neg_sampling_ratio: 2.0
        num_neighbors:
            - 20
            - 10
        shuffle: true
    val_test:
        batch_size: 2048
        num_neighbors:
            - 20
            - 10
        shuffle: false
model:
    hidden_channels: 16
    movie_feat_dim: 403
    dropout: 0.4
    emb_dropout: 0.3
optimizer:
    lr: 0.001
scheduler:
    mode: "max"
    factor: 0.5
    patience: 3
    threshold: 0.00001
    min_lr: 0.0000001
early_stopping:
    patience: 5
    min_delta: 0.0001
    best_model_path: "results/best_model_16.pth"
